tardis-sn/stardis

- stardis/base.py
- stardis/io/base.py
- stardis/opacities/base.py
- stardis/opacities/broadening.py
- stardis/opacities/voigt.py
- stardis/plasma/base.py
- stardis/transport/base.py
This should redo PR #21 but handling the merge conflicts correctly.
> Added docstrings

- stardis/base.py
- stardis/opacities/base.py
- stardis/opacities/broadening.py
- stardis/plasma/base.py
> Independent broadening calculations

- stardis/base.py
- stardis/config_schema.yml
- stardis/opacities/base.py
> Inputs in frequency or wavelength space

- stardis/base.py
- stardis/opacities/base.py
- stardis/opacities/util.py
> Change opacity source parsing

- stardis/base.py
- stardis/model/base.py
- stardis/opacities/base.py
- stardis/opacities/broadening.py
- stardis/opacities/util.py
- stardis/plasma/base.py
- stardis/transport/base.py
> Docstrings and naming changes

- setup.cfg
> Add config_schema.yml to setup.cfg

- setup.cfg
- stardis/plasma/base.py
> Fixing create_stellar_plasma bug

- .github/workflows/build-docs.yml
**Type:** :memo: `documentation`
This adds the GitHub workflow to build the Sphinx documentation. The documentation currently builds successfully, but is not published yet. 
[Here is a link to the rendered website](https://smokestacklightnin.github.io/stardis/index.html) It is based on whatever I push most recently (on any branch). I would like to have separate instances for separate branches but don't know how.
> Build Sphinx Documentation Using GitHub Actions

- docs/index.rst
- docs/running_the_code.rst
**Type:** :memo: `documentation`
This pull request includes the Running the Code section of the documentation from the old docs
> Sphinx docs section running the code

- .github/workflows/codestyle.yml
- stardis/__init__.py
- stardis/plasma/base.py
- stardis/tests/test_example.py
**Type:** :roller_coaster: `infrastructure`
I basically copied the Black code formatting [test from TARDIS](https://github.com/tardis-sn/tardis/blob/master/.github/workflows/codestyle.yml) almost virbatim. The only changes were to the names "tardis" to "stardis"
> Add Black Code Formatting test

- docs/bibliography.rst
- docs/conf.py
- docs/index.rst
- docs/stardis.bib
**Type:**  :memo: `documentation`
This uses `sphinxcontrib.bibtex` to pretty print the bibliography from the [`stardis.bib`](https://github.com/smokestacklightnin/stardis/blob/sphinx-docs-section-bib/docs/stardis.bib) bib file. 
> Add Bibliography to Sphinx Docs

- stardis/io/model/tests/test_model_io.py
**Type:**  :vertical_traffic_light: `testing`
This pull request includes a refactoring of the marcs model tests.
Part of the refactoring includes adding a pytest fixture that provides the data file path
> Add marcs test fixture

- stardis/io/model/marcs.py
- stardis/model/base.py
- stardis/model/composition/base.py
Adding structure for composition class
> Add composition

- docs/installation.rst
**Type:** :memo: `documentation`
This pull request adds a [note in the installation docs](https://smokestacklightnin.github.io/stardis/branch/docs/downloading-and-installation/environment-comment/installation.html#downloading-and-installing-stardis) about activating the virtual environment before installing stardis
There are also very minor changes to the [non-developers install instructions](https://smokestacklightnin.github.io/stardis/branch/docs/downloading-and-installation/environment-comment/installation.html#for-non-developers) ([original](https://tardis-sn.github.io/stardis/installation.html#for-non-developers)). 
> Minor clarifying changes to installation docs

- stardis/base.py
- stardis/io/model/marcs.py
- stardis/model/base.py
- stardis/opacities/base.py
- stardis/opacities/broadening.py
- stardis/plasma/base.py
- stardis/transport/base.py
**Type:** :beetle: `bugfix` | :memo: `documentation` 
This PR mostly removes mentions of shells throughout the code. It also removes the read_marcs_to_fv() function which was deprecated.
The PR also contains various small bug fixes like imports that were never used or variables that have been defined but have not been used. 
The quickstart notebook was rerun and the same output was produced.
No functional code changes should have been made. 
> change references of shell to depth point throughout code

- stardis/radiation_field/opacities/opacities_solvers/broadening.py
- stardis/radiation_field/opacities/tests/test_broadening.py
**Type:** :rocket: `feature` 
This pull request adds CUDA JIT to  `calc_gamma_linear_stark()`.
> Add CUDA JIT to `calc_gamma_linear_stark()`

- stardis/model/base.py
- stardis/radiation_field/opacities/opacities_solvers/base.py
I got tired of looking at inconsistent array intializations, so I went through and gave stellar_model an effective shape attribute to be used throughout the code. 
It's possible that the property is supposed to belong to the geometry class, but I opted for it to belong to the top level class to be more easily accessed throughout the various parts of the code.
> Cleanup model shape use

- stardis/io/model/tests/test_model_io.py
**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`
Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.
Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 
> Change Marcs model file handling in test_model_io.py

- stardis/radiation_field/opacities/opacities_solvers/tests/test_broadening.py
- stardis/radiation_field/radiation_field_solvers/base.py
Van noort 2001 suggests to do this. Linearly interpolating biases to higher opacities.
> interpolate opacities in log space for rad trans

- stardis/plasma/base.py
Fixes plasma being broken by https://github.com/tardis-sn/tardis/pull/2675
> fix plasma for estimator restructure

- .github/workflows/benchmarks.yml
- .github/workflows/build-docs.yml
- .github/workflows/tests.yml
- docs/installation.rst
- stardis_env3.yml
- stardis_env3_cuda.yml
Pins the tardis version for now. Will unpin again soon when tardis plasma is stable.
> pin tardis

- .github/workflows/lfs-cache.yml
**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`
Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.
Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 
> Workflow typo fixes

- docs/installation.rst
Just adds the arm lock file to possible installation choices.
> add arm lock file to installation

- .github/workflows/benchmarks.yml
- .github/workflows/lfs-cache.yml
- asv.conf.json
- benchmarks/benchmark_config.yml
- benchmarks/run_stardis.py
**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`
Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.
Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 
> Fix benchmarks

- .github/workflows/release.yml
> Zenodo fixes
