- stardis/opacities/base.py
**Type:** :beetle: `bugfix` 
Calc_alpha_at_nu is expected to return a tuple but returned an int
- [x ] Testing pipeline
> Fix returning int when tuple expected in calc_alpha_at_nu

- docs/physics/physics_of_stardis.rst
**Type:**  :memo: `documentation` 
I received a verbal request top resize the images in the physics docs to have 500 px widths. This pull request accomplishes that.
> Change Physics docs image widths to 500 px

- docs/conf.py
**Type:** :memo: `documentation`
This pull request changes the Sphinx documentation theme from Alabaster to RTD to match the [TARDIS docs](https://tardis-sn.github.io/tardis/).
[Github page for the RTD theme](https://github.com/readthedocs/sphinx_rtd_theme)
> Change Sphinx docs theme from Alabaster to RTD

- .github/workflows/clean-docs.yml
**Type:**  :memo: `documentation` | :roller_coaster: `infrastructure`
This commit ports the [`clean-docs.yml`](https://github.com/tardis-sn/tardis/blob/master/.github/workflows/clean-docs.yml) from the tardis repository without changes into the stardis repo. No changes are necessary. 
> Add clean-docs.yml

- docs/running_the_code.rst
This pull request adds links to the data files in the [Running the Code](https://tardis-sn.github.io/stardis/running_the_code.html) section of the docs. 
There are a couple of other minor formatting changes as well, namely fixing bullet points and superscripts. 
> Add links to data files, and a fix for bullet points and superscripts in Running the Code docs

- .github/workflows/build-docs.yml
**Type:**  :memo: `documentation` | :roller_coaster: `infrastructure`
This commit causes the Sphinx docs workflow to be triggered only on the main branch of tardis-sn/stardis or if it is not on a repo owned by tardis-sn. This is so that other branches do not trigger the docs to be run
@sonachitchyan @jvshields @jaladh-singhal @smithis7
> Run build-docs.yml Only on Main Branch of tardis-sn/stardis

- stardis/transport/base.py
**Type:** :beetle: `bugfix` 
This pull request fixes a minor typo in raytracing
> Fix typo in raytrace

- stardis/opacities/tests/test_voigt.py
**Type:** :vertical_traffic_light: `testing` 
This pull request adds a few basic tests to the [`opacities.voigt`](https://github.com/tardis-sn/stardis/blob/main/stardis/opacities/voigt.py) module. The tests are parametrized to test several input values and also include tests to raise errors when a division by zero is attempted. 
[How to parametrize pytest fixtures and test functions](https://docs.pytest.org/en/7.3.x/how-to/parametrize.html)
[Examples for parametrized test functions](https://docs.pytest.org/en/7.3.x/example/parametrize.html#paramexamples)
> Add some basic tests for the Voigt module

- stardis/base.py
- stardis/io/model/marcs.py
- stardis/model/base.py
- stardis/model/composition/base.py
**Type:** | :rocket: `feature` | :roller_coaster: `infrastructure`
This PR should probably have been broken into two pull requests. It does two primary things.
marcs.py has been changed to add a to_composition() method that uses the Composition class added in [PR 103 ](https://github.com/tardis-sn/stardis/pull/103). It also adds a to_stellar_model() method that outputs a geometry, composition, and temperatures, though this method is currently not called anywhere. 
The second thing this PR does is alter the StellarModel class to hold the composition, allowing for the previous to_stellar_model() method to exist, and updates read_marcs_to_fv() correctly to handle this change. 
The read_marcs_model import in stardis/model/base.py was moved inside read_marcs_to_fv() to avoid a circular import. …
> Change abundances to mass fraction

- stardis/base.py
- stardis/io/model/marcs.py
- stardis/model/base.py
- stardis/model/geometry/radial1d.py
- stardis/opacities/base.py
- stardis/opacities/broadening.py
- stardis/plasma/base.py
- stardis/transport/base.py
**Type:**  :rocket: `feature` | :biohazard: `breaking change` | :roller_coaster: `infrastructure`
This PR attaches swaps the old model created by read_marcs_to_fv() out and hooks up the new model reader to the run_stardis() function. This effectively implements much of the restructure work with the new infrastructure, and so it also includes changing the code in many places to read information from the new model structure. 
Future PRs need to change the Configuration schema to allow for general model reading, as the current code only allows for unzipped MARCS models, so the configuration should allow to specify whether the input model is gzipped or not. 
Additionally, I have left many comments around the code pointing out parts that need cleaning or changing, because they are misleading …
> Swap to new model

- stardis/transport/base.py
**Type:** | :rocket: `feature` | :vertical_traffic_light: `testing` | 
This PR adds the next term of the van noort 2001 equation we solve to do radiative transfer. It seems like it changes our answer at the 0.1% level, which is small enough that it's not a particularly significant change, but the radiative transfer equation is also such a small part of the runtime of the code that I think it's worth doing by default. If people think it's necessary, we can make this an option that can be turned on or off, but I think we should just adopt it into the code always because the performance increase is negligible. I've run the benchmarks a couple times and have not seen a statistically significant change in runtime. 
As a note, if we can get [PR …
> Add next term van noort intensity solver

- stardis/base.py
- stardis/config_schema.yml
Allows the config to take a gzipped argument in model and passes that to the model reader.
This allows the config to point to any plane-parallel model obtained from https://marcs.oreme.org/
> add arg to the config_schema.yml file for gzipped and hook up in run_stardis

- .github/workflows/build-docs.yml
**Type:** | :roller_coaster: `infrastructure`
This includes TARDIS bot actions to leave comments for success or failure of the build-docs workflow.
[Original code](https://github.com/tardis-sn/tardis/blob/334c6fe7324b78599f74f1e266be0de0e3abbf79/.github/workflows/build-docs.yml#L134-L178)
> Add TARDIS Bot comments from TARDIS Repo

- stardis/opacities/tests/test_voigt.py
- stardis/opacities/voigt.py
**Type:**  :rocket: `feature`
This pull request implements CUDA JITting for Faddeeva. The non-CUDA version of Faddeeva is also refactored. 
The associated tests are included.
This pull request should be merged (hopefully immediately) ***after*** pull request #110 
> Add CUDA GPU JIT compilation to `faddeeva()`

- stardis/base.py
Adds units to Stardis output. They're just simply added on the end as appropriate, which feels a little hacky, but they generally cannot be carried along deeper for njitting purposes. 
If there is a better suggestion for how to do this I'd love to hear. 
> add units to stardis outputs

- .github/workflows/benchmarks.yml
- benchmarks/config_schema.yml
- benchmarks/run_stardis.py
**Type:** :beetle: `bugfix` | :rocket: `feature` | :vertical_traffic_light: `testing` :roller_coaster: `infrastructure`
This PR adds workflow to benchmark internal stardis functions like raytrace
> Benchmark internal STARDIS functions

- benchmarks/run_stardis.py
**Type:** :beetle: `bugfix`
An incorrect config parameter was passed to one of the benchmarks which was causing the [benchmark workflow to fail.](https://github.com/tardis-sn/stardis/actions/runs/5904330002/job/16016165642)
> Fix breaking benchmark pipeline

- stardis/opacities/tests/test_voigt.py
- stardis/opacities/voigt.py
**Type:**  :rocket: `feature` 
This pull request refactors `voigt_profile()` and adds CUDA JIT compilation to the same function. Basic unit tests are also included. 
This pull request should be merged (hopefully immediately) after pull request #107 
> Refactor and add CUDA JIT compilation to `voigt_profile()`

- stardis/opacities/broadening.py
- stardis/opacities/tests/test_broadening.py
**Type:** :rocket: `feature` 
This pull request adds CUDA JIT to `calc_n_effective()`
It is ready for immediate merging after the merging of Pull Request #118 
> Add CUDA JIT to `calc_n_effective()`

- .github/workflows/benchmarks.yml
**Type:** :beetle: `bugfix`
Benchmarking workflow is not pushing results to the [intended repository ](https://github.com/tardis-sn/stardis-benchmarks).
> Fix benchmarking action not pushing results to the results repo

- stardis/radiation_field/radiation_field_solvers/base.py
**Type:** :beetle: `bugfix` 
The W2 weight was not calculated in the large and small tau case, so the code would crash in those cases. This adds the appropriate weight calculation for W2. This branch was created on top of the radiation field branch so that should probably be merged first for ease of conflicts.
> add w2 in the small and large delta tau case

- benchmarks/benchmark_config.yml
- benchmarks/run_stardis.py
Small changes, mostly making the wavelength range smaller for benchmarking and matching the lines considered wavelength range to the wavelengths of the simulation. 
The should mainly speed up the benchmarks for a small quality of life improvement.
> small benchmarking cleanup

- stardis/base.py
- stardis/config_schema.yml
- stardis/radiation_field/base.py
**Type:** | :roller_coaster: `infrastructure`
Changes the STARDISOutput object in line with the various restructure of the parts of the simulation. Now, instead of returning many different attributes of the radiation field, it can return the model, plasma, and radiation field entirely as separate objects. I have updated the config schema to allow for requesting these different parts, defaulting to not returning the model or plasma, but return the plasma field. 
> change STARDISOutput to return the three objects of the simulation

- .github/workflows/tests.yml
**Type:** :beetle: `bugfix` 
Remove tests that use cuda because GitHub Actions does not provide GPUs.
> Remove tests that use cuda because GitHub doesn't run them

- benchmarks/run_stardis.py
I tracked down a bug in the benchmarks - why they haven't been able to run for awhile.
It's a small change, but the config is necessary now to create the plasma and that wasn't passed along to the benchmark model creation. Hopefully the benchmarks will run again now with this.
> attempt benchmark fix

- stardis/config_schema.yml
- stardis/plasma/base.py
- stardis/radiation_field/opacities/opacities_solvers/base.py
This calculates opacities with the short form of a vald linelist. Allows us to directly compare to korg (since as far as we can tell they can't use the long-form linelist). Also modifies the config schema to accept a shortlist specification so that the new calculation can be used. 
At some point soon it'd be nice to get proper regression tests going, since that's the easiest way to test the plasma. This seems to me like the best way to test the different plasmas and calculated opacities.
> Shortlist calculation

- stardis/conftest.py
- stardis/radiation_field/opacities/opacities_solvers/base.py
- stardis/radiation_field/opacities/opacities_solvers/tests/test_opacties_solvers.py
- stardis/tests/stardis_test_config_broadening.yml
Broadening range restrictions (the space around a line where the line was considered as adding to opacity) were previously non-functional. This meant that all of our simulations, especially the broader ones, scaled highly non-linearly with the wavelength range because all lines were considered as adding to all opacities at all wavelengths or frequencies.
This pr makes that broadening range restriction functional and should create a large speedup for broad wavelength simulations.
The pr also includes a bit of cleaning to make the function generally neater and remove a couple of non-functional calculations (a lot of resetting indices of dataframes that didn't make any functional change).
> Improve broadening range treatment

- stardis/radiation_field/opacities/opacities_solvers/base.py
Small pr to rectify a small inefficiency I came across in the code. 
This just changes a bulky for loop to use a more efficient numpy implementation.
> remove alpha_electron for loop

- .github/workflows/benchmarks.yml
This should stop the stardis-benchmarks repo from being overwritten. The workflow pushes new commits to a .asv subdirectory instead of the root of the repository.
> give benchmarks.yml a target directory

- stardis/radiation_field/base.py
- stardis/radiation_field/opacities/base.py
I introduced a bug when originally creating the Opacities object in the calc_total_opacities() method. This is a more sane way of calculating total opacities with an initialization that doesn't just point the total opacities to the first entry of the dictionary.
> fix bug that overwrote first entry in opacities_dict

- stardis/radiation_field/opacities/opacities_solvers/base.py
I changed some code to use vectorization and appropriate broadcasting to eliminate some for loops. For an 1000 angstrom wide spectrum with 0.01 angstrom wide bins, this reduces the calculation time by a factor of ~2. Considering that this is most computationally expensive part of the code, this offers a substantial speedup to stardis. 
This change doesn't seem to show much in the benchmarks because we use a very small simulation in that case. This mainly gives significant speedups for large simulations that calculate many lines at many frequency bins.
> Internal speedup for calculating line opacities

- stardis/radiation_field/opacities/opacities_solvers/base.py
- stardis/radiation_field/opacities/opacities_solvers/broadening.py
- stardis/radiation_field/opacities/opacities_solvers/tests/test_opacities_solvers.py
- stardis/radiation_field/opacities/opacities_solvers/util.py
- stardis/tests/stardis_test_config.yml
- stardis/tests/stardis_test_config_broadening.yml
The broadening calculation needed a lot of cleaning. This is the beginning of that cleaning/speedup. A large portion of the PR is getting rid of things being saved to variables and then immediately used in functions, or things being returned by functions for no reason, or things being converted to numpy arrays from dataframes and then being accessed in odd ways that make far more sense to be located directly in the dataframes. 
Another part of the pr is getting rid of the nested for loop inside the function. The calculations are now done with appropriate array broadcasting.
> Cleanup calculate broadening

- stardis/radiation_field/radiation_field_solvers/base.py
Had a large bug in the radiative transfer pull request from #168. An if statement should have been an elif so the further terms in the equation where being overwritten. This fixes that, and also handles the case of the last depth point by assuming the source function beyond the final depth point is equal to the source function at the last depth point.
> fix bug in radiative transfer equation

- stardis/base.py
- stardis/config_schema.yml
- stardis/conftest.py
- stardis/radiation_field/radiation_field_solvers/base.py
- stardis/tests/stardis_test_config_broadening.yml
- stardis/tests/stardis_test_config_parallel.yml
- stardis/tests/test_stardis_full.py
I made a mistake with PR #176 where I didn't correctly adapt the radiative transfer equation for the last calculation. It tried to access a tau out of bounds of the tau array. I didn't realize it because apparently the njit decorator can hide that and complete the calculation quietly anyway, probably accessing something else in memory that doesn't belong to the array. 
Good to know, and this gives us back a tiny bit more of the missing flux. 
I should mention, for adapting the equation I just used tau[j+1] = tau[j], which should be ok enough of an approximation. The other choice would be to have tau[j+1] = 0 (since you're not moving through any material anymore). If there are any strong opinions on this I would love to hear it. 
---------------------------------------
This PR got much …
> fix bug with last depth point out of bounds error

- benchmarks/benchmark_config.yml
- benchmarks/run_stardis.py
- stardis/base.py
- stardis/config_schema.yml
- stardis/conftest.py
- stardis/radiation_field/opacities/opacities_solvers/base.py
- stardis/radiation_field/radiation_field_solvers/base.py
- stardis/tests/stardis_test_config_parallel.yml
- stardis/tests/test_stardis_full.py
This expands PR #178 to allow for parallelization of the slowest part of the code. It should not be merged before that pull request.
> Line opacity parallelization

- stardis/radiation_field/opacities/opacities_solvers/voigt.py
Our voigt profile disagrees with the scipy voigt profile by a couple of factors. This PR adds documentation to explain where our disagreements come, including references to where things are defined differently. It also changes the constant attached to our gamma passed in to the lorentzian, where I think the disagreement comes from a defined dispersion parameter versus the lorentzian gamma. It all still seems a bit nebulous, but this change gives us correct lines. I attach an h-alpha comparison to korg for comparison. 
There's still some disagreement at the bottom of the line that comes from treating linear stark h-alpha broadening somewhat incorrectly, but this change fixes the wings.
> Update voigt profile and add documentation

- stardis/base.py
- stardis/conftest.py
- stardis/io/base.py
- stardis/plasma/base.py
- stardis/radiation_field/base.py
This PR restructures the high level run_stardis() function to only be a helper function that calls a couple other functions scattered throughout the code. This makes it much easier to effectively run the function on your own so you can parse a model, edit the model as a python object, and then run the rest of the function. 
This is intended to make it easier to modify specific abundances and investigate their impacts on lines in the spectrum.
Still need to make an easy helper function that takes in the stellar model, and allows you to request an abundance of some given element, and then rescale the rest of the elements appropriately.
> Expose model params

- stardis/base.py
- stardis/io/base.py
- stardis/io/model/__init__.py
This lets the user add additional arguments to the run_stardis function to update or overwrite config values. It allows for much more flexible simulations at the python level, like running simulations in a loop with a list of different elemental rescaling values. It specifically bypasses the need to remake or change the config if you want to change some individual part of the simulation.
> allow user to specify config values to overwrite in run_stardis function

- docs/installation.rst
- docs/physics/physics_of_stardis.rst
- docs/quickstart/quickstart.ipynb
The installation instructions didn't actually work because they ask you to make an environment from a lock file, but they don't tell you how to get that lock file. They also mentioned a pinned TARDIS version, which we moved away from. This fixes those issues.
> update installation instructions and small changes in physics_of_stardis

- .github/workflows/benchmarks.yml
- asv.conf.json
- benchmarks/benchmark_config.yml
I broke the benchmarks again because the config file it wants use the now removed broadening max and min. 
This also cleans up the asv workflow a little.
> fix benchmarks config

- stardis/plasma/base.py
The tardis opacities refactor moved TauSobolev. This PR just fixes our import.
> fix TauSobolev import

- stardis/io/base.py
The previous code would fail if a string was provided because it attempts to iterate through the keys provide which works if the keys provided are a list. This fails because it attempts to iterate through the string (setting each character as an item in the config). This catches the case of a string being passed.
> handle case of strings in config update

- stardis/plasma/base.py
A recent tardis plasma restructure makes the plasma no longer accept radiative temperature as an input. This updates stardis to work with current tardis plasma.
> fix plasma for tardis restructure

- stardis/base.py
- stardis/io/base.py
When I added the feature for people to pass additional information into run_stardis() to let people modify the config before running, I did it in a very weird way, having people pass the keys and values for a dictionary separately, instead of just ad a dictionary object. This changes it so the user can just specify a dictionary and is much simpler.
> simplify updating config logic

- stardis/plasma/base.py
- stardis/radiation_field/opacities/opacities_solvers/util.py
Scipy's linear1d interpolator is deprecated, so we're using numpy's instead. This also has the benefit of fixing an out of bounds error that sometimes came up to use the behavior we want of fill values being the first and last entry.
> use np interpolator instead of scipy

- stardis/config_schema.yml
- stardis/io/base.py
- stardis/io/model/marcs.py
- stardis/model/base.py
- stardis/radiation_field/opacities/opacities_solvers/broadening.py
- stardis/radiation_field/opacities/opacities_solvers/tests/test_broadening.py
There's also an option in the config to disable microturbulence. 
Here's a solar spectrum of H-Alpha with microturbulence read from the Marcs model
Here's that with microturbulence disabled.
> add microturbulence to simulation

- stardis/radiation_field/opacities/opacities_solvers/util.py
Small typo from last pull request. Files changed should be pretty self-evident for this fix.
> fix typo pointing to wrong opacity source in logger message

- stardis/config_schema.yml
- stardis/plasma/base.py
- stardis/plasma/molecules.py
- stardis/radiation_field/opacities/opacities_solvers/base.py
- stardis/radiation_field/opacities/opacities_solvers/broadening.py
This PR lets us use vald broadening parameters and interpolate them to the plasma, rather than calculate them ourselves. On top of the more direct comparison this lets us make to other codes, this also allows us to handle auto-ionization lines (see the line around 5172.4 angstroms below).
> vald broadening implementation

- docs/installation.rst
**Type:** :beetle: `bugfix`
Replace the broken link `https://mamba.readthedocs.io/en/latest/installation.html` with the correct working link `https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html`
Closes #240
> Fixes the broken Mamba installation link on "Downloading and Installation" Page in docs

- benchmarks/run_stardis.py
- stardis/conftest.py
- stardis/io/base.py
- stardis/io/schemas/config_schema.yml
- stardis/io/schemas/input_model.yml
- stardis/tests/stardis_test_config.yml
**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`
Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.
Fixes #249 
> Changes the field name from model to input_model in config schema

- stardis/io/model/mesa.py
- stardis/model/base.py
Mesa models were broken because of a unit mismatch. This small patch makes them work again. 
I also created issue #262 as a reminder to make mesa tests so they don't get quietly broken again.
> fix mesa microturbulence units

- stardis/io/schemas/result_options.yml
This object can be very big, and most people probably will want to interact with the spectrum, not the full radiation field. 
I think I changed this before, but @RyanGroneck might have accidentally flipped it back on when restructuring the schemas.
> turn off rad field default
